### ISSUE TITLE
No such property: username for class: java.lang.String in android\build.gradle (package.json)

### ISSUE THREAD

**Issue by chuysbz** [cuidamimascota/react-native-conekta#1]
Buen día,

Estoy intentando compilar para el emulador de Android en Windows y estoy recibiendo el siguiente error:

```
Build file 'C:\APP DIRECTORY\node_modules\@cuidamimascota\react-native-conekta\android\build.gradle' line: 100

* What went wrong:
A problem occurred configuring project ':@cuidamimascota_react-native-conekta'.
> No such property: username for class: java.lang.String

```
Revisando el archivo gradle mencionado en el error, noto que se busca en el archivo package.json (C:\APP DIRECTORY\node_modules@cuidamimascota\react-native-conekta\package.json) el objeto author con propiedades username y name.

**build.gradle**

```
def configureReactNativePom(def pom) {
    def packageJson = new groovy.json.JsonSlurper().parseText(file('../package.json').text)

    pom.project {
        name packageJson.title
        artifactId packageJson.name
        version = packageJson.version
        group = "com.reactlibrary"
        description packageJson.description
        url packageJson.repository.baseUrl

        licenses {
            license {
                name packageJson.license
                url packageJson.repository.baseUrl + '/blob/master/' + packageJson.licenseFilename
                distribution 'repo'
            }
        }

        developers {
            developer {
                id packageJson.author.username
                name packageJson.author.name
            }
        }
    }
}
```

 sin embargo en dicho archivo el la propiedad author es un string.

**package.json**

```
{
  "name": "@cuidamimascota/react-native-conekta",
  "title": "React Native Conekta",
  "version": "3.1.0",
  "description": "react native conekta",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/cuidamimascota/react-native-conekta.git",
    "baseUrl": "https://github.com/cuidamimascota/react-native-conekta"
  },
  "keywords": [
    "react-native",
    "react-native-conekta"
  ],
  "author": "binwilly <https://github.com/binwilly>",
  "license": "MIT",
  "licenseFilename": "LICENSE",
  "peerDependencies": {
    "react": "^16.8.1",
    "react-native": ">=0.60.0-rc.0 <1.0.x"
  },
  "devDependencies": {
    "react": "^16.9.0",
    "react-native": "^0.61.5"
  },
  "bugs": {
    "url": "https://github.com/cuidamimascota/react-native-conekta/issues"
  },
  "homepage": "https://github.com/cuidamimascota/react-native-conekta#readme",
  "directories": {
    "example": "example"
  }
}
```

Realmente he estado investigando para descartar que sea un tema de mi entorno pero hasta ahora la única forma en que pude compilar fue modificando el json de la dependencia. 

Revisando en otros proyectos, en los archivos package.json se incluye la propiedad author como string y no como objeto, así que posiblemente sea necesario corregir el build.gradle para que no intente tomarlo como objeto, pero realmente no soy experto en gradle así que no me atrevo a realizar algún cambio.

Esta dependencia para react native realmente me ha sido muy útil pues es la única que funciona con versiones recientes del framework. Gracias de antemano.

**Comment by binwilly** [comment]
Hola @soyjesus gracias por el feedback en un rato subo con el cambio en el package json.

**Comment by binwilly** [comment]
en la version 3.1.1 esta el cambio, si se arregla con ese cambio cierro el issue

**Comment by chuysbz** [comment]
Muchas gracias ya se solucionó con la actualización.
